/* The following code was generated by JFlex 1.4_pre3 on 7/1/16 12:53 AM */

package atlc;

import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.Location;

/**
 * This class represents the scanner.
 */



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4_pre3
 * on 7/1/16 12:53 AM from the specification file
 * <tt>file:/Users/jpo/Programming/itba/tla/cafe/jflex/Scanner.flex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int YY_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] yycmap = {
    15, 15, 15, 15, 15, 15, 15, 15, 15,  3,  1,  0,  0,  2, 15, 15, 
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,  0,  0,  0,  0, 
    13, 33,  0,  0, 14,  0, 34,  0, 27, 28, 31, 29,  0, 30,  0, 32, 
     6,  7,  7,  7,  7,  7,  7,  7,  7,  7, 39,  0, 36, 38, 37,  0, 
     0, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,  0,  0,  0,  0, 14, 
     0, 14, 19, 14, 22,  9, 25, 14, 26, 17, 14, 14, 20, 16, 11, 12, 
    14, 14, 21, 10, 18, 14, 24, 23, 14,  8, 14,  0, 35,  0,  5, 15
  };


  /** 
   * Translates a state to a row index in the transition table (packed version)
   */
  final private static String yy_rowMap_packed = 
    "\0\0\0\50\0\50\0\120\0\50\0\50\0\170\0\50\0\240\0\310"+
    "\0\360\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258"+
    "\0\u0280\0\50\0\50\0\50\0\50\0\50\0\50\0\u02a8\0\u02d0\0\u02f8"+
    "\0\u0320\0\u0348\0\u0370\0\50\0\u0398\0\u03c0\0\u03e8\0\50\0\50\0\u0410"+
    "\0\u0438\0\50\0\u0460\0\u0488\0\u04b0\0\50\0\50\0\50\0\50\0\u04d8"+
    "\0\50\0\50\0\50\0\50\0\50\0\50\0\50\0\50\0\50\0\50"+
    "\0\50\0\u0500\0\50\0\50";

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int [] yy_rowMap = yy_unpack_rowMap(yy_rowMap_packed);


  /** 
   * Unpacks the compressed row translation table.
   *
   * @param packed   the packed row translation table
   * @return         the unpacked row translation table
   */
  private static int [] yy_unpack_rowMap(String packed) {
    int [] map = new int[128];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int high = ((int) packed.charAt(i++)) << 16;
      map[j++] = high | packed.charAt(i++);
    }
    return map;
  }
  /** 
   * The packed transition table of the DFA (part 0)
   */
  private static final String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\2\1\13\1\14\1\2\1\15\2\2\1\16"+
    "\1\17\1\2\1\20\1\21\1\22\1\23\1\24\1\2"+
    "\1\25\1\2\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\51\0"+
    "\1\3\63\0\1\43\40\0\2\11\51\0\1\44\60\0"+
    "\1\45\41\0\1\46\7\0\1\47\23\0\1\50\1\0"+
    "\6\50\5\51\1\50\1\51\1\50\13\51\15\50\13\0"+
    "\1\52\47\0\1\53\60\0\1\54\35\0\1\55\63\0"+
    "\1\56\47\0\1\57\46\0\1\60\2\0\1\61\1\0"+
    "\1\62\46\0\1\63\64\0\1\64\43\0\1\65\50\0"+
    "\1\66\52\0\1\67\47\0\1\70\47\0\1\71\1\0"+
    "\1\43\1\72\46\43\12\0\1\46\62\0\1\73\22\0"+
    "\1\50\1\0\47\50\1\0\4\50\7\51\1\50\15\51"+
    "\15\50\22\0\1\74\40\0\1\75\65\0\1\76\42\0"+
    "\1\77\54\0\1\100\16\0";

  /** 
   * The transition table of the DFA
   */
  private static final int yytrans [] = yy_unpack();


  /* error codes */
  private static final int YY_UNKNOWN_ERROR = 0;
  private static final int YY_ILLEGAL_STATE = 1;
  private static final int YY_NO_MATCH = 2;
  private static final int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  private static final String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final byte YY_ATTRIBUTE[] = {
     0,  9,  9,  1,  9,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  1,  1,  1,  1,  1, 
     1,  9,  0,  0,  0,  9,  9,  1,  1,  9,  0,  0,  1,  9,  9,  9, 
     9,  0,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  0,  9,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    private ComplexSymbolFactory symbolFactory;
    StringBuffer string = new StringBuffer();

    public Scanner(java.io.InputStream inputStream, ComplexSymbolFactory symbolFactory) {
        this(inputStream);
        this.symbolFactory = symbolFactory;
    }

    public Symbol createSymbol(String plaintext, int code) {
        System.out.println("parsed: " + plaintext);
        return symbolFactory.newSymbol(plaintext, code,
            new Location("", yyline + 1, yycolumn + 1, yychar),
            new Location("", yyline + 1, yycolumn + yylength(), yychar));
    }

    public Symbol createSymbol(String plaintext, int code, Object object) {
        System.out.println("parsed: " + plaintext +" :: " + object);
        return symbolFactory.newSymbol(plaintext, code,
            new Location("", yyline + 1, yycolumn + 1, yychar),
            new Location("", yyline + 1, yycolumn + yylength(), yychar),
            object);
    }

    public Symbol createSymbol(String plaintext, int code, Object object, int buffLength) {
        return symbolFactory.newSymbol(plaintext, code,
            new Location(yyline + 1, yycolumn + yylength() - buffLength, yychar + yylength() - buffLength),
            new Location(yyline + 1, yycolumn + yylength(), yychar + yylength()),
            object);
    }

    public Boolean createBoolean(String str) {
        if (!str.equals("yes") && !str.equals("no")) {
            throw new IllegalArgumentException();
        }
        return str.equals("yes");
    }

    public void printError(String symbol) {
        System.err.println("Invalid symbol <" + string + ">");
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1320];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 25: 
          {  return createSymbol("Times",sym.TIMES);  }
        case 65: break;
        case 41: 
          {  return createSymbol("Main", sym.MAIN);  }
        case 66: break;
        case 44: 
          {  return createSymbol("Else", sym.ELSE);  }
        case 67: break;
        case 45: 
          {  return createSymbol("Read", sym.READ);  }
        case 68: break;
        case 62: 
          {  return createSymbol("While", sym.WHILE);  }
        case 69: break;
        case 24: 
          {  return createSymbol("Minus", sym.MINUS);  }
        case 70: break;
        case 5: 
          {  return createSymbol("Space", sym.SPACE);  }
        case 71: break;
        case 47: 
          {  return createSymbol("Write", sym.WRITE);  }
        case 72: break;
        case 56: 
          {  return createSymbol("Equal to", sym.EQ);  }
        case 73: break;
        case 55: 
          {  return createSymbol("greater than or equal to", sym.GE);  }
        case 74: break;
        case 48: 
          {  return createSymbol("Write var", sym.WRITE_VAR);  }
        case 75: break;
        case 54: 
          {  return createSymbol("Lower than or equal to", sym.LE);  }
        case 76: break;
        case 57: 
          {  /* Do Nothing */	 }
        case 77: break;
        case 58: 
          {  return createSymbol("String", sym.TYPE_STR);  }
        case 78: break;
        case 31: 
          {  return createSymbol("Greater than", sym.GT);  }
        case 79: break;
        case 60: 
          {  return createSymbol("Boolean", sym.TYPE_BOOL);  }
        case 80: break;
        case 46: 
          {  return createSymbol("Do", sym.DO);  }
        case 81: break;
        case 50: 
          {  return createSymbol("If", sym.IF);  }
        case 82: break;
        case 51: 
          {  return createSymbol("Not equal to", sym.NEQ);  }
        case 83: break;
        case 53: 
          {  return createSymbol("Or", sym.OR);  }
        case 84: break;
        case 2: 
        case 3: 
          {  return createSymbol("End of Line", sym.EOL);  }
        case 85: break;
        case 59: 
          {  return createSymbol("Integer", sym.TYPE_INT);  }
        case 86: break;
        case 7: 
        case 8: 
          {  return createSymbol("Integer", sym.LIT_INT, new Integer(yytext()));  }
        case 87: break;
        case 63: 
          {  return createSymbol("Else-If", sym.ELSE_IF);  }
        case 88: break;
        case 27: 
          {  return createSymbol("Not", sym.NOT);  }
        case 89: break;
        case 23: 
          {  return createSymbol("Plus",sym.PLUS);  }
        case 90: break;
        case 4: 
          {  return createSymbol("Tab", sym.TAB);  }
        case 91: break;
        case 52: 
          {  return createSymbol("And", sym.AND);  }
        case 92: break;
        case 38: 
          {  return createSymbol("Write new line", sym.EOL);  }
        case 93: break;
        case 22: 
          {  return createSymbol("Right Bracket",sym.RPAREN);  }
        case 94: break;
        case 12: 
        case 39: 
          {  return createSymbol("String", sym.LIT_STR, yytext());  }
        case 95: break;
        case 21: 
          {  return createSymbol("Left Bracket",sym.LPAREN);  }
        case 96: break;
        case 40: 
          {  return createSymbol("Var Name", sym.VAR_NAME, yytext());  }
        case 97: break;
        case 1: 
        case 6: 
        case 9: 
        case 10: 
        case 11: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 28: 
        case 29: 
        case 32: 
          {  throw new Error("Illegal character <" + yytext() + ">"); }
        case 98: break;
        case 37: 
          {  return createSymbol("Boolean", sym.LIT_BOOL, createBoolean(yytext()));  }
        case 99: break;
        case 30: 
          {  return createSymbol("Lower Than", sym.LT);  }
        case 100: break;
        case 26: 
          {  return createSymbol("Divide", sym.DIVIDE);  }
        case 101: break;
        case 33: 
          {  return createSymbol("Assign", sym.ASSIGN);  }
        case 102: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     System.out.println("parsed: EOF");
    return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
