
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Sat Jun 25 00:18:42 GMT-03:00 2016
//----------------------------------------------------

package atlc;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int ELSE = 10;
  public static final int GTR = 14;
  public static final int PLUS = 3;
  public static final int RPAREN = 6;
  public static final int SEMI = 2;
  public static final int WHILE = 8;
  public static final int IF = 9;
  public static final int LPAREN = 5;
  public static final int GTR_EQ = 17;
  public static final int DO = 7;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int DIVIDE = 12;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int LESS_EQ = 16;
  public static final int EQ = 13;
  public static final int NOT_EQ = 18;
  public static final int LESS = 15;
}

