
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Fri Jul 01 00:43:52 ART 2016
//----------------------------------------------------

package atlc;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SPACE = 35;
  public static final int DIVIDE = 6;
  public static final int LIT_INT = 21;
  public static final int WRITE_VAR = 29;
  public static final int GE = 17;
  public static final int LPAREN = 31;
  public static final int MINUS = 5;
  public static final int WRITE = 28;
  public static final int RPAREN = 32;
  public static final int NOT = 18;
  public static final int AND = 20;
  public static final int LT = 15;
  public static final int TYPE_STR = 25;
  public static final int OR = 19;
  public static final int TAB = 34;
  public static final int TYPE_INT = 24;
  public static final int EOL = 33;
  public static final int PLUS = 3;
  public static final int MAIN = 2;
  public static final int IF = 9;
  public static final int ELSE_IF = 11;
  public static final int LE = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 13;
  public static final int EQ = 12;
  public static final int TIMES = 4;
  public static final int ELSE = 10;
  public static final int READ = 30;
  public static final int WHILE = 8;
  public static final int VAR_NAME = 27;
  public static final int LIT_BOOL = 22;
  public static final int TYPE_BOOL = 26;
  public static final int GT = 14;
  public static final int DO = 7;
  public static final int LIT_STR = 23;
}

