
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package atlc;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RET = 3;
  public static final int ELSE = 20;
  public static final int LIT_STR = 18;
  public static final int RPAREN = 14;
  public static final int UNARY_LOGIC_OPERATOR = 26;
  public static final int WHILE = 22;
  public static final int ARITHMETIC_OPERATOR = 23;
  public static final int READ_LINE = 10;
  public static final int WRITE_LINE = 11;
  public static final int DEDENT = 6;
  public static final int IF = 19;
  public static final int LPAREN = 13;
  public static final int WRITE = 12;
  public static final int EOL = 7;
  public static final int DO = 21;
  public static final int TYPE = 8;
  public static final int LIT_INT = 16;
  public static final int COMMA = 15;
  public static final int SP = 4;
  public static final int EOF = 0;
  public static final int FUNC = 2;
  public static final int VAR_NAME = 9;
  public static final int ASSIGN_TYPE = 28;
  public static final int BOOLEAN_OPERATOR = 24;
  public static final int error = 1;
  public static final int ASSIGN = 27;
  public static final int LIT_BOOL = 17;
  public static final int LOGIC_OPERATOR = 25;
  public static final int INDENT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNC",
  "RET",
  "SP",
  "INDENT",
  "DEDENT",
  "EOL",
  "TYPE",
  "VAR_NAME",
  "READ_LINE",
  "WRITE_LINE",
  "WRITE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "LIT_INT",
  "LIT_BOOL",
  "LIT_STR",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "ARITHMETIC_OPERATOR",
  "BOOLEAN_OPERATOR",
  "LOGIC_OPERATOR",
  "UNARY_LOGIC_OPERATOR",
  "ASSIGN",
  "ASSIGN_TYPE"
  };

  /* non terminals */
  static final int expr_str = 18;
  static final int expr = 15;
  static final int method = 2;
  static final int stmt_io = 12;
  static final int stmt_exit = 13;
  static final int expr_bool = 16;
  static final int method_argument = 6;
  static final int block = 20;
  static final int program = 0;
  static final int stmt_if_maybe_else = 9;
  static final int stmt_list = 4;
  static final int expr_int = 17;
  static final int stmt_if = 10;
  static final int stmt_while = 11;
  static final int stmt_method_call = 14;
  static final int stmt_def_maybe_assign = 7;
  static final int method_argument_list = 19;
  static final int stmt_assign = 8;
  static final int stmt = 5;
  static final int param_list = 3;
  static final int method_list = 1;
}

